Deploy host must fail if host is not updated
When deploying a host, the PatchAgent is previously notified by the
changes in the feed repo and uses this information to deploy the
change in the host. If for some reason (e.g. service failure, bug)
the PatchAgent is not notified, the command 'software deploy host'
will fail and it will raise a 900.021 alarm.

Testing Plan:
PASS: Block the PatchAgent notification and run
      'software deploy start <patch-id>'
PASS: Run 'software deploy host <hostname>
PASS: See in the user output:
      Error: Host installation failed on <hostname>
PASS: Run 'fm alarm-list' and check if 900.021 alarm exists
PASS: Run 'ostree log --repo=/sysroot/ostree/repo/ starlingx'
      and check that the patch was not applied

Story: 2010676
Task: 50611

Change-Id: I09755eb4e5692524f352ee82e9effcb1e78ead14
Signed-off-by: Lindley Vieira <lindley.vieira@windriver.com>